---
- name: Install Chocolatey on Windows
  hosts: windows
  tasks:
    - name: Check if Chocolatey is installed
      win_command: choco -v
      register: choco_version
      ignore_errors: yes

    - name: Install Chocolatey if not installed
      win_shell: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
      when: choco_version.rc != 0

    - name: Update Chocolatey if already installed
      win_shell: choco upgrade chocolatey -y
      when: choco_version.rc == 0